# -*- coding: utf-8 -*-
"""listofteachers

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xIFH4wf1AYPM3W0c7gq_5bnbwkyw33GV
"""

import pandas as pd

teacher = pd.DataFrame({
    'FISh': ['Qadamova Zulayho', 'Karimov Sardor', 'Rahmonov Ozodbek', 'Azizov Iskandar', 'Ibragimov N', 'Muxtarov N', 'Xusanova M', 'Torayeva M', 'Odina Sobirovna'],
    'Fani': ['Suniy intellekt asoslari', 'Suniy intellekt asoslari', 'Sotib olish tamoyillari', 'Buxgalteriya hisobi', 'Mikroiqtisodiyot', 'Kiberxavsizlik asoslari', 'Sotib olish tamoyillari', 'Tutor', '----'],
    "Mashg'ulot turi": ['Amaliy', 'Maruza', 'Amaliy', 'Amaliy', 'Maruza', 'Maruza', 'Amaliy', 'Amaliy', '----']
})

print(teacher)

teacher.to_excel("listofteachers's.xlsx")